### ISSUE TITLE
"For development purposes only"

### ISSUE THREAD

**Issue by karihigh** [joeyklee/streetview-mapper-docs#1]
Hello! 
I just signed up to the Streetview Mapper and when I signed in, it showed the following modal from Google:
"This page can't load Google Maps correctly
Do you own this website?"

Also the map to navigate has a watermark that says "For development purposes only" and the streetview is in negative colors (which looks kind of cool) and has the same watermark. 

I was able to save a location, but neither the dashboard or the public show the image previews.

**Comment by joeyklee** [comment]
Hi @karihigh - thanks for posting this issue. 

## Issue
Quite likely your screen looks like this:

<img width="1431" alt="Screen Shot 2020-04-01 at 8 41 33 AM" src="https://user-images.githubusercontent.com/3622055/78138317-b559d800-73f4-11ea-9911-0eb5fcf842df.png">

If oyu open your If you open y our developer console in the browser, you'll see the following error message:

<img width="503" alt="Screen Shot 2020-04-01 at 8 41 11 AM" src="https://user-images.githubusercontent.com/3622055/78138401-d6222d80-73f4-11ea-8a7b-32b36b1057e4.png">


```
You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started
```


<img width="1431" alt="Screen Shot 2020-04-01 at 8 41 39 AM" src="https://user-images.githubusercontent.com/3622055/78138352-c4408a80-73f4-11ea-9ac1-ddc76ab1bcfd.png">


## Solution

You can follow this link: You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started 

In order to activate your API key, you will also need to include your billing information. Google maps API is a pay-as-you-go/freemium style so you'll only get charged if/after you pass the daily limits. You will still need to add some billing info to your account though. 

Hope this helps!

**Comment by karihigh** [comment]
Solved! 🌈

**Comment by joeyklee** [comment]
Prima!
